annotations:
  category: Infrastructure
  images: |
    - name: memcached-exporter
      image: docker.io/bitnami/memcached-exporter:0.13.0-debian-11-r121
    - name: memcached
      image: docker.io/bitnami/memcached:1.6.21-debian-11-r107
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r90
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.6.21
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Memcached is an high-performance, distributed memory object caching system,
  generic in nature, but intended for use in speeding up dynamic web applications
  by alleviating database load.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/memcached/img/memcached-stack-220x234.png
keywords:
- memcached
- cache
name: memcached
version: 6.6.6
